spring:
    zipkin:
    base-url: http://${ZIPKIN_URL:localhost}:9411
  rabbitmq:
    username: guest
    password: guest
    host: ${RABBIT_URL:localhost}
    port: 5672
eureka:
  client:
    service-url:
      defaultZone: http://${EUREKA_URL:localhost}:8761/eureka/
management:
  health:
    circuitbreakers:
      enabled: true
  info:
    env:
      enabled: true
  endpoints:
    web:
      exposure:
        include: health,info,circuitbreakers,circuitbreakerevents
  endpoint:
    health:
      show-details: always
info:
  author: Lucas Ferreira Nogueira
  mail: lucas.ferreiranogueira@gmail.com
message: Realizando a avaliação de especialização em Backend Java
