spring:
  zipkin:
    base-url: http://zipkin-service:9411/
  rabbitmq:
    username: guest
    password: guest
    host: rabbit-service
    port: 5672
eureka:
  client:
    service-url:
      defaultZone: http://eureka-server:8761/eureka/
management:
  health:
    circuitbreakers:
      enabled: true
  info:
    env:
      enabled: true
  endpoints:
    web:
      exposure:
        include: health,info,circuitbreakers,circuitbreakerevents
  endpoint:
    health:
      show-details: always
info:
  author: Lucas Ferreira Nogueira
  mail: lucas.ferreiranogueira@gmail.com
  cel: (11) 95953-8062
# server:
#  port: ${PORT:9999}
message: Realizando a avaliação de especialização em Backend Java

queue:
  serie-service: queue-serie-service
  movie-service: queue-movie-service
