server:
  port: 8083
  servlet:
    context-path: /catalog-api
spring:
  zipkin:
    base-url: http://${ZIPKIN_URL:localhost}:9411
eureka:
  client:
    service-url:
      defaultZone: http://${EUREKA_URL:localhost}:8761/eureka/
