server:
  port: 8083
  servlet:
    context-path: /catalog-api
queue:
  movie-service: queue-movie-service
  serie-service: queue-serie-service
spring:
  zipkin:
    base-url: http://${ZIPKIN_URL:localhost}:9411
eureka:
  client:
    service-url:
      defaultZone: http://${EUREKA_URL:localhost}:8761/eureka/
management:
  info:
    env:
      enabled: true
  endpoints:
    web:
      exposure:
        include: health,info,metrics
  endpoint:
    health:
      show-details: always
resilience4j:
  circuitbreaker:
    instances:
      movie-service:
        allowHealthIndicatorToFail: false
        registerHealthIndicator: true
        slidingWindowType: COUNT_BASED
        slidingWindowSize: 2
        failueRateThreshold: 10
        waitDurationInOpenState: 10000
        permittedNumberOfCalssInHalfOpenState: 2
        automaticTransitionFromOpenToHalfIfOpenEnabled: true
      serie-service:
        allowHealthIndicatorToFail: false
        registerHealthIndicator: true
        slidingWindowType: COUNT_BASED
        slidingWindowSize: 2
        failueRateThreshold: 10
        waitDurationInOpenState: 10000
        permittedNumberOfCalssInHalfOpenState: 2
        automaticTransitionFromOpenToHalfIfOpenEnabled: true
retry:
    instances:
      serie-service:
        maxAttempts: 2
        waitDuration: 5000
        retryExceptions:
          - feign.FeignException$ServiceUnavailable
          - feign.FeignException$InternalServerError
          - org.springframework.web.client.HttpServerErrorException
          - java.util.concurrent.TimeoutException
          - java.io.IOException
      movie-service:
        maxAttempts: 2
        waitDuration: 5000
        retryExceptions:
          - feign.FeignException$ServiceUnavailable
          - feign.FeignException$InternalServerError
          - org.springframework.web.client.HttpServerErrorException
          - java.util.concurrent.TimeoutException
          - java.io.IOException