server:
  port: 8083
  servlet:
    context-path: /catalog-api
queue:
  movie-service: queue-movie-service
  serie-service: queue-serie-service
spring:
  zipkin:
    base-url: http://${ZIPKIN_URL:localhost}:9411
eureka:
  client:
    service-url:
      defaultZone: http://${EUREKA_URL:localhost}:8761/eureka/
management:
  info:
    env:
      enabled: true
  endpoints:
    web:
      exposure:
        include: health,info,metrics
  endpoint:
    health:
      show-details: always