server:
  port: 8080
spring:
  cloud:
    gateway:
      routes:
        - id: catalogRoute
          uri: lb://CATALOG-SERVICE
          predicates:
            - Path=/catalog-api/**
        - id: movieRoute
          uri: lb://MOVIE-SERVICE
          predicates:
            - Path=/movie-api/**
        - id: serieRoute
          uri: lb://serie-service
          predicates:
            - Path=/serie-api/**
  zipkin:
    base-url: http://${ZIPKIN_URL:localhost}:9411
management:
  info:
    env:
      enabled: true
  endpoints:
    web:
      exposure:
        include: health,info,metrics
  endpoint:
    health:
      show-details: always
eureka:
  client:
    service-url:
      defaultZone: http://${EUREKA_URL:localhost}:8761/eureka/